import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.coolingservicemelbourne.com.au";
  const currentDate = new Date().toISOString();

  // Main pages
  const mainPages = [
    {
      url: baseUrl,
      lastModified: currentDate,
      changeFrequency: "daily" as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.9,
    },

    {
      url: `${baseUrl}/brands`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
  ];

  // Service pages
  const servicePages = [
    {
      url: `${baseUrl}/service`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/service-details`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    // Split System Services
    {
      url: `${baseUrl}/service/split-system`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/split-system/split-system-installation-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/split-system/split-system-repair-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/split-system/split-system-service-tune-up-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/split-system/emergency-split-system-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    // Ducted System Services
    {
      url: `${baseUrl}/service/ducted-system`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/ducted-system/ducted-system-installation-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/ducted-system/ducted-system-repair-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/ducted-system/ducted-system-service-maintenance-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/ducted-system/duct-cleaning-airflow-balancing-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/ducted-system/emergency-ducted-system-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    // Evaporative System Services
    {
      url: `${baseUrl}/service/evaporative-system`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/evaporative-system/evaporative-cooling-installation-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/evaporative-system/evaporative-system-repair-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/evaporative-system/seasonal-service-replacement-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/evaporative-system/water-management-leak-repair-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service/evaporative-system/emergency-evaporative-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    // Emergency Services
    {
      url: `${baseUrl}/service/emergency`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/emergency/emergency-split-system-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/emergency/emergency-ducted-system-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/emergency/emergency-evaporative-cooling-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/emergency/emergency-aircon-repair-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service/emergency/24-hour-cooling-repairs-melbourne`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
  ];

  // Service areas pages
  const serviceAreaPages = [
    {
      url: `${baseUrl}/service-areas`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/service-areas/melbourne-suburbs`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
  ];

  // Service area suburbs
  const serviceAreas = [
    "armadale",
    "ashwood",
    "attwood",
    "avonsleigh",
    "badger-creek",
    "bayswater",
    "baxter",
    "beaconsfield",
    "belgrave",
    "bentleigh",
    "bentleigh-east",
    "berwick",
    "beaumaris",
    "bittern",
    "black-rock",
    "blackburn-north",
    "blairgowrie",
    "boneo",
    "boronia",
    "botanic-ridge",
    "box-hill",
    "briar-hill",
    "broadmeadows",
    "brighton",
    "brighton-east",
    "bundoora",
    "burwood-3125",
    "burwood-chadstone",
    "burwood-east",
    "caulfield",
    "chadstone",
    "chelsea",
    "chelsea-heights",
    "chirnside-park",
    "clayton",
    "clayton-south",
    "clyde",
    "clyde-north",
    "dandenong",
    "dandenong-north",
    "dandenong-south",
    "doncaster",
    "doncaster-east",
    "donvale",
    "doveton",
    "eaglehawk",
    "epping",
    "essendon",
    "essendon-fields",
    "fawkner",
    "ferntree-gully",
    "frankston",
    "frankston-north",
    "frankston-south",
    "gembrook",
    "glen-waverley",
    "greensborough",
    "hallam",
    "hampton",
    "hampton-park",
    "heatherton",
    "highett",
    "hillside",
    "hoppers-crossing",
    "keilor",
    "keilor-downs",
    "keilor-lodge",
    "kings-park",
    "knoxfield",
    "lakes-entrance",
    "lalor",
    "langwarrin",
    "lara",
    "laverton",
    "laverton-north",
    "lilydale",
    "little-river",
    "macleod",
    "maroondah",
    "melbourne-cbd",
    "melbourne-airport",
    "melbourne-east",
    "melbourne-south",
    "melton",
    "melton-south",
    "mordialloc",
    "mornington",
    "mount-eliza",
    "mount-evelyn",
    "mount-waverley",
    "narre-warren",
    "narre-warren-north",
    "narre-warren-south",
    "north-melbourne",
    "northcote",
    "oakleigh",
    "oakleigh-south",
    "pakenham",
    "pakenham-south",
    "pakenham-upper",
    "parkdale",
    "pascoe-vale",
    "pascoe-vale-south",
    "point-cook",
    "point-leo",
    "port-melbourne",
    "ringwood",
    "ringwood-east",
    "ringwood-north",
    "rivervale",
    "rowville",
    "sandringham",
    "scoresby",
    "seaford",
    "skye",
    "somerville",
    "south-melbourne",
    "south-morang",
    "southbank",
    "springvale",
    "springvale-south",
    "st-albans",
    "st-kilda",
    "st-kilda-east",
    "sunshine",
    "sunshine-north",
    "sunshine-west",
    "tarneit",
    "tooradin",
    "toorak",
    "truemans",
    "tyabb",
    "upper-ferntree-gully",
    "wantirna",
    "wantirna-south",
    "werribee",
    "werribee-south",
    "wheelers-hill",
    "yallambie",
    "yarra-glen",
    "yarra-junction",
    "yarraville",
    "yellingbo",
    "yering",
  ];

  const serviceAreaSuburbPages = serviceAreas.map((area) => ({
    url: `${baseUrl}/service-areas/${area}`,
    lastModified: currentDate,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  // Self-care pages
  const selfCarePages = [
    {
      url: `${baseUrl}/self-care`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
  ];

  // Self-care brand pages
  const selfCareBrands = [
    "daikin",
    "mitsubishi",
    "lg",
    "panasonic",
    "samsung",
    "fujitsu",
    "carrier",
    "toshiba",
    "hitachi",
    "sharp",
    "haier",
    "gree",
    "tcl",
    "kelvinator",
    "rheem",
    "braemar",
    "bonaire",
    "coolair",
    "breezair",
    "convair",
  ];

  const selfCareBrandPages = selfCareBrands.map((brand) => ({
    url: `${baseUrl}/self-care/${brand}`,
    lastModified: currentDate,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // Individual brand pages
  const brandNames = [
    "daikin",
    "mitsubishi",
    "panasonic",
    "samsung",
    "fujitsu",
    "carrier",
    "toshiba",
    "kelvinator",
    "rheem",
    "braemar",
    "bonaire",
  ];

  const brandPages = brandNames.map((brand) => ({
    url: `${baseUrl}/brands/${brand}`,
    lastModified: currentDate,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [
    ...mainPages,
    ...servicePages,
    ...serviceAreaPages,
    ...serviceAreaSuburbPages,
    ...selfCarePages,
    ...selfCareBrandPages,
    ...brandPages,
  ];
}
